apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejemplo001
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ejemplo001
  template:
    metadata:
      labels:
        app: ejemplo001
    spec:
      containers:
        - name: ejemplo001
          image: ejemplo001:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000