apiVersion: v1
kind: Service
metadata:
  name: ejemplo001-service
  namespace: demo
spec:
  selector:
    app: ejemplo001
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP